using System.Collections.ObjectModel;

namespace WeatherApp
{
  public class Country
  {
    public string CountryCode;
    public string CountryName;
    //This returns the the CountryName (CountryCode) instead of WeatherApp.Country, which is used for display in the Country Picker drop-down.
    public override string ToString() => $"{CountryName} ({CountryCode})";

    public static ObservableCollection<Country> Init()
    {
      ObservableCollection<Country> CountryList = new ObservableCollection<Country>();

      CountryList.Add(new Country() { CountryCode = "AF", CountryName = "Afgahanistan" });
      CountryList.Add(new Country() { CountryCode = "AX", CountryName = "Åland Islands" });
      CountryList.Add(new Country() { CountryCode = "AL", CountryName = "Albania" });
      CountryList.Add(new Country() { CountryCode = "DZ", CountryName = "Algeria" });
      CountryList.Add(new Country() { CountryCode = "AS", CountryName = "American Samoa" });
      CountryList.Add(new Country() { CountryCode = "AD", CountryName = "Andorra" });
      CountryList.Add(new Country() { CountryCode = "AO", CountryName = "Angola" });
      CountryList.Add(new Country() { CountryCode = "AI", CountryName = "Anguilla" });
      CountryList.Add(new Country() { CountryCode = "AQ", CountryName = "Antarctica" });
      CountryList.Add(new Country() { CountryCode = "AG", CountryName = "Antigua and Barbuda" });
      CountryList.Add(new Country() { CountryCode = "AR", CountryName = "Argentina" });
      CountryList.Add(new Country() { CountryCode = "AM", CountryName = "Armenia" });
      CountryList.Add(new Country() { CountryCode = "AW", CountryName = "Aruba" });
      CountryList.Add(new Country() { CountryCode = "AU", CountryName = "Australia" });
      CountryList.Add(new Country() { CountryCode = "AT", CountryName = "Austria" });
      CountryList.Add(new Country() { CountryCode = "AZ", CountryName = "Azerbaijan" });
      CountryList.Add(new Country() { CountryCode = "BS", CountryName = "Bahamas" });
      CountryList.Add(new Country() { CountryCode = "BH", CountryName = "Bahrain" });
      CountryList.Add(new Country() { CountryCode = "BD", CountryName = "Bangladesh" });
      CountryList.Add(new Country() { CountryCode = "BB", CountryName = "Barbados" });
      CountryList.Add(new Country() { CountryCode = "BY", CountryName = "Belarus" });
      CountryList.Add(new Country() { CountryCode = "BE", CountryName = "Belgium" });
      CountryList.Add(new Country() { CountryCode = "BZ", CountryName = "Belize" });
      CountryList.Add(new Country() { CountryCode = "BJ", CountryName = "Benin" });
      CountryList.Add(new Country() { CountryCode = "BM", CountryName = "Bermuda" });
      CountryList.Add(new Country() { CountryCode = "BT", CountryName = "Bhutan" });
      CountryList.Add(new Country() { CountryCode = "BO", CountryName = "Bolivia, Plurinational State of" });
      CountryList.Add(new Country() { CountryCode = "BQ", CountryName = "Bonaire, Sint Eustatius and Saba" });
      CountryList.Add(new Country() { CountryCode = "BA", CountryName = "Bosnia and Herzegovina" });
      CountryList.Add(new Country() { CountryCode = "BW", CountryName = "Botswana" });
      CountryList.Add(new Country() { CountryCode = "BV", CountryName = "Bouvet Island" });
      CountryList.Add(new Country() { CountryCode = "BR", CountryName = "Brazil" });
      CountryList.Add(new Country() { CountryCode = "IO", CountryName = "British Indian Ocean Territory" });
      CountryList.Add(new Country() { CountryCode = "BN", CountryName = "Brunei Darussalam" });
      CountryList.Add(new Country() { CountryCode = "BG", CountryName = "Bulgaria" });
      CountryList.Add(new Country() { CountryCode = "BF", CountryName = "Burkina Faso" });
      CountryList.Add(new Country() { CountryCode = "BI", CountryName = "Burundi" });
      CountryList.Add(new Country() { CountryCode = "KH", CountryName = "Cambodia" });
      CountryList.Add(new Country() { CountryCode = "CM", CountryName = "Cameroon" });
      CountryList.Add(new Country() { CountryCode = "CA", CountryName = "Canada" });
      CountryList.Add(new Country() { CountryCode = "CV", CountryName = "Cape Verde" });
      CountryList.Add(new Country() { CountryCode = "KY", CountryName = "Cayman Islands" });
      CountryList.Add(new Country() { CountryCode = "CF", CountryName = "Central African Republic" });
      CountryList.Add(new Country() { CountryCode = "TD", CountryName = "Chad" });
      CountryList.Add(new Country() { CountryCode = "CL", CountryName = "Chile" });
      CountryList.Add(new Country() { CountryCode = "CN", CountryName = "China" });
      CountryList.Add(new Country() { CountryCode = "CX", CountryName = "Christmas Island" });
      CountryList.Add(new Country() { CountryCode = "CC", CountryName = "Cocos (Keeling) Islands" });
      CountryList.Add(new Country() { CountryCode = "CO", CountryName = "Colombia" });
      CountryList.Add(new Country() { CountryCode = "KM", CountryName = "Comoros" });
      CountryList.Add(new Country() { CountryCode = "CG", CountryName = "Congo" });
      CountryList.Add(new Country() { CountryCode = "CD", CountryName = "Congo, the Democratic Republic of the" });
      CountryList.Add(new Country() { CountryCode = "CK", CountryName = "Cook Islands" });
      CountryList.Add(new Country() { CountryCode = "CR", CountryName = "Costa Rica" });
      CountryList.Add(new Country() { CountryCode = "CI", CountryName = "Côte d'Ivoire" });
      CountryList.Add(new Country() { CountryCode = "HR", CountryName = "Croatia" });
      CountryList.Add(new Country() { CountryCode = "CU", CountryName = "Cuba" });
      CountryList.Add(new Country() { CountryCode = "CW", CountryName = "Curaçao" });
      CountryList.Add(new Country() { CountryCode = "CY", CountryName = "Cyprus" });
      CountryList.Add(new Country() { CountryCode = "CZ", CountryName = "Czech Republic" });
      CountryList.Add(new Country() { CountryCode = "DK", CountryName = "Denmark" });
      CountryList.Add(new Country() { CountryCode = "DJ", CountryName = "Djibouti" });
      CountryList.Add(new Country() { CountryCode = "DM", CountryName = "Dominica" });
      CountryList.Add(new Country() { CountryCode = "DO", CountryName = "Dominican Republic" });
      CountryList.Add(new Country() { CountryCode = "EC", CountryName = "Ecuador" });
      CountryList.Add(new Country() { CountryCode = "EG", CountryName = "Egypt" });
      CountryList.Add(new Country() { CountryCode = "SV", CountryName = "El Salvador" });
      CountryList.Add(new Country() { CountryCode = "GQ", CountryName = "Equatorial Guinea" });
      CountryList.Add(new Country() { CountryCode = "ER", CountryName = "Eritrea" });
      CountryList.Add(new Country() { CountryCode = "EE", CountryName = "Estonia" });
      CountryList.Add(new Country() { CountryCode = "ET", CountryName = "Ethiopia" });
      CountryList.Add(new Country() { CountryCode = "FK", CountryName = "Falkland Islands (Malvinas)" });
      CountryList.Add(new Country() { CountryCode = "FO", CountryName = "Faroe Islands" });
      CountryList.Add(new Country() { CountryCode = "FJ", CountryName = "Fiji" });
      CountryList.Add(new Country() { CountryCode = "FI", CountryName = "Finland" });
      CountryList.Add(new Country() { CountryCode = "FR", CountryName = "France" });
      CountryList.Add(new Country() { CountryCode = "GF", CountryName = "French Guiana" });
      CountryList.Add(new Country() { CountryCode = "PF", CountryName = "French Polynesia" });
      CountryList.Add(new Country() { CountryCode = "TF", CountryName = "French Southern Territories" });
      CountryList.Add(new Country() { CountryCode = "GA", CountryName = "Gabon" });
      CountryList.Add(new Country() { CountryCode = "GM", CountryName = "Gambia" });
      CountryList.Add(new Country() { CountryCode = "GE", CountryName = "Georgia" });
      CountryList.Add(new Country() { CountryCode = "DE", CountryName = "Germany" });
      CountryList.Add(new Country() { CountryCode = "GH", CountryName = "Ghana" });
      CountryList.Add(new Country() { CountryCode = "GI", CountryName = "Gibraltar" });
      CountryList.Add(new Country() { CountryCode = "GR", CountryName = "Greece" });
      CountryList.Add(new Country() { CountryCode = "GL", CountryName = "Greenland" });
      CountryList.Add(new Country() { CountryCode = "GD", CountryName = "Grenada" });
      CountryList.Add(new Country() { CountryCode = "GP", CountryName = "Guadeloupe" });
      CountryList.Add(new Country() { CountryCode = "GU", CountryName = "Guam" });
      CountryList.Add(new Country() { CountryCode = "GT", CountryName = "Guatemala" });
      CountryList.Add(new Country() { CountryCode = "GG", CountryName = "Guernsey" });
      CountryList.Add(new Country() { CountryCode = "GN", CountryName = "Guinea" });
      CountryList.Add(new Country() { CountryCode = "GW", CountryName = "Guinea-Bissau" });
      CountryList.Add(new Country() { CountryCode = "GY", CountryName = "Guyana" });
      CountryList.Add(new Country() { CountryCode = "HT", CountryName = "Haiti" });
      CountryList.Add(new Country() { CountryCode = "HM", CountryName = "Heard Island and McDonald Islands" });
      CountryList.Add(new Country() { CountryCode = "VA", CountryName = "Holy See (Vatican City State)" });
      CountryList.Add(new Country() { CountryCode = "HN", CountryName = "Honduras" });
      CountryList.Add(new Country() { CountryCode = "HK", CountryName = "Hong Kong" });
      CountryList.Add(new Country() { CountryCode = "HU", CountryName = "Hungary" });
      CountryList.Add(new Country() { CountryCode = "IS", CountryName = "Iceland" });
      CountryList.Add(new Country() { CountryCode = "IN", CountryName = "India" });
      CountryList.Add(new Country() { CountryCode = "ID", CountryName = "Indonesia" });
      CountryList.Add(new Country() { CountryCode = "IR", CountryName = "Iran, Islamic Republic of" });
      CountryList.Add(new Country() { CountryCode = "IQ", CountryName = "Iraq" });
      CountryList.Add(new Country() { CountryCode = "IE", CountryName = "Ireland" });
      CountryList.Add(new Country() { CountryCode = "IM", CountryName = "Isle of Man" });
      CountryList.Add(new Country() { CountryCode = "IL", CountryName = "Israel" });
      CountryList.Add(new Country() { CountryCode = "IT", CountryName = "Italy" });
      CountryList.Add(new Country() { CountryCode = "JM", CountryName = "Jamaica" });
      CountryList.Add(new Country() { CountryCode = "JP", CountryName = "Japan" });
      CountryList.Add(new Country() { CountryCode = "JE", CountryName = "Jersey" });
      CountryList.Add(new Country() { CountryCode = "JO", CountryName = "Jordan" });
      CountryList.Add(new Country() { CountryCode = "KZ", CountryName = "Kazakhstan" });
      CountryList.Add(new Country() { CountryCode = "KE", CountryName = "Kenya" });
      CountryList.Add(new Country() { CountryCode = "KI", CountryName = "Kiribati" });
      CountryList.Add(new Country() { CountryCode = "KP", CountryName = "Korea, Democratic People's Republic of" });
      CountryList.Add(new Country() { CountryCode = "KR", CountryName = "Korea, Republic of" });
      CountryList.Add(new Country() { CountryCode = "KW", CountryName = "Kuwait" });
      CountryList.Add(new Country() { CountryCode = "KG", CountryName = "Kyrgyzstan" });
      CountryList.Add(new Country() { CountryCode = "LA", CountryName = "Lao People's Democratic Republic" });
      CountryList.Add(new Country() { CountryCode = "LV", CountryName = "Latvia" });
      CountryList.Add(new Country() { CountryCode = "LB", CountryName = "Lebanon" });
      CountryList.Add(new Country() { CountryCode = "LS", CountryName = "Lesotho" });
      CountryList.Add(new Country() { CountryCode = "LR", CountryName = "Liberia" });
      CountryList.Add(new Country() { CountryCode = "LY", CountryName = "Libya" });
      CountryList.Add(new Country() { CountryCode = "LI", CountryName = "Liechtenstein" });
      CountryList.Add(new Country() { CountryCode = "LT", CountryName = "Lithuania" });
      CountryList.Add(new Country() { CountryCode = "LU", CountryName = "Luxembourg" });
      CountryList.Add(new Country() { CountryCode = "MO", CountryName = "Macao" });
      CountryList.Add(new Country() { CountryCode = "MK", CountryName = "Macedonia, the Former Yugoslav Republic of" });
      CountryList.Add(new Country() { CountryCode = "MG", CountryName = "Madagascar" });
      CountryList.Add(new Country() { CountryCode = "MW", CountryName = "Malawi" });
      CountryList.Add(new Country() { CountryCode = "MY", CountryName = "Malaysia" });
      CountryList.Add(new Country() { CountryCode = "MV", CountryName = "Maldives" });
      CountryList.Add(new Country() { CountryCode = "ML", CountryName = "Mali" });
      CountryList.Add(new Country() { CountryCode = "MT", CountryName = "Malta" });
      CountryList.Add(new Country() { CountryCode = "MH", CountryName = "Marshall Islands" });
      CountryList.Add(new Country() { CountryCode = "MQ", CountryName = "Martinique" });
      CountryList.Add(new Country() { CountryCode = "MR", CountryName = "Mauritania" });
      CountryList.Add(new Country() { CountryCode = "MU", CountryName = "Mauritius" });
      CountryList.Add(new Country() { CountryCode = "YT", CountryName = "Mayotte" });
      CountryList.Add(new Country() { CountryCode = "MX", CountryName = "Mexico" });
      CountryList.Add(new Country() { CountryCode = "FM", CountryName = "Micronesia, Federated States of" });
      CountryList.Add(new Country() { CountryCode = "MD", CountryName = "Moldova, Republic of" });
      CountryList.Add(new Country() { CountryCode = "MC", CountryName = "Monaco" });
      CountryList.Add(new Country() { CountryCode = "MN", CountryName = "Mongolia" });
      CountryList.Add(new Country() { CountryCode = "ME", CountryName = "Montenegro" });
      CountryList.Add(new Country() { CountryCode = "MS", CountryName = "Montserrat" });
      CountryList.Add(new Country() { CountryCode = "MA", CountryName = "Morocco" });
      CountryList.Add(new Country() { CountryCode = "MZ", CountryName = "Mozambique" });
      CountryList.Add(new Country() { CountryCode = "MM", CountryName = "Myanmar" });
      CountryList.Add(new Country() { CountryCode = "NA", CountryName = "Namibia" });
      CountryList.Add(new Country() { CountryCode = "NR", CountryName = "Nauru" });
      CountryList.Add(new Country() { CountryCode = "NP", CountryName = "Nepal" });
      CountryList.Add(new Country() { CountryCode = "NL", CountryName = "Netherlands" });
      CountryList.Add(new Country() { CountryCode = "NC", CountryName = "New Caledonia" });
      CountryList.Add(new Country() { CountryCode = "NZ", CountryName = "New Zealand" });
      CountryList.Add(new Country() { CountryCode = "NI", CountryName = "Nicaragua" });
      CountryList.Add(new Country() { CountryCode = "NE", CountryName = "Niger" });
      CountryList.Add(new Country() { CountryCode = "NG", CountryName = "Nigeria" });
      CountryList.Add(new Country() { CountryCode = "NU", CountryName = "Niue" });
      CountryList.Add(new Country() { CountryCode = "NF", CountryName = "Norfolk Island" });
      CountryList.Add(new Country() { CountryCode = "MP", CountryName = "Northern Mariana Islands" });
      CountryList.Add(new Country() { CountryCode = "NO", CountryName = "Norway" });
      CountryList.Add(new Country() { CountryCode = "OM", CountryName = "Oman" });
      CountryList.Add(new Country() { CountryCode = "PK", CountryName = "Pakistan" });
      CountryList.Add(new Country() { CountryCode = "PW", CountryName = "Palau" });
      CountryList.Add(new Country() { CountryCode = "PS", CountryName = "Palestine, State of" });
      CountryList.Add(new Country() { CountryCode = "PA", CountryName = "Panama" });
      CountryList.Add(new Country() { CountryCode = "PG", CountryName = "Papua New Guinea" });
      CountryList.Add(new Country() { CountryCode = "PY", CountryName = "Paraguay" });
      CountryList.Add(new Country() { CountryCode = "PE", CountryName = "Peru" });
      CountryList.Add(new Country() { CountryCode = "PH", CountryName = "Philippines" });
      CountryList.Add(new Country() { CountryCode = "PN", CountryName = "Pitcairn" });
      CountryList.Add(new Country() { CountryCode = "PL", CountryName = "Poland" });
      CountryList.Add(new Country() { CountryCode = "PT", CountryName = "Portugal" });
      CountryList.Add(new Country() { CountryCode = "PR", CountryName = "Puerto Rico" });
      CountryList.Add(new Country() { CountryCode = "QA", CountryName = "Qatar" });
      CountryList.Add(new Country() { CountryCode = "RE", CountryName = "Réunion" });
      CountryList.Add(new Country() { CountryCode = "RO", CountryName = "Romania" });
      CountryList.Add(new Country() { CountryCode = "RU", CountryName = "Russian Federation" });
      CountryList.Add(new Country() { CountryCode = "RW", CountryName = "Rwanda" });
      CountryList.Add(new Country() { CountryCode = "BL", CountryName = "Saint Barthélemy" });
      CountryList.Add(new Country() { CountryCode = "SH", CountryName = "Saint Helena, Ascension and Tristan da Cunha" });
      CountryList.Add(new Country() { CountryCode = "KN", CountryName = "Saint Kitts and Nevis" });
      CountryList.Add(new Country() { CountryCode = "LC", CountryName = "Saint Lucia" });
      CountryList.Add(new Country() { CountryCode = "MF", CountryName = "Saint Martin (French part)" });
      CountryList.Add(new Country() { CountryCode = "PM", CountryName = "Saint Pierre and Miquelon" });
      CountryList.Add(new Country() { CountryCode = "VC", CountryName = "Saint Vincent and the Grenadines" });
      CountryList.Add(new Country() { CountryCode = "WS", CountryName = "Samoa" });
      CountryList.Add(new Country() { CountryCode = "SM", CountryName = "San Marino" });
      CountryList.Add(new Country() { CountryCode = "ST", CountryName = "Sao Tome and Principe" });
      CountryList.Add(new Country() { CountryCode = "SA", CountryName = "Saudi Arabia" });
      CountryList.Add(new Country() { CountryCode = "SN", CountryName = "Senegal" });
      CountryList.Add(new Country() { CountryCode = "RS", CountryName = "Serbia" });
      CountryList.Add(new Country() { CountryCode = "SC", CountryName = "Seychelles" });
      CountryList.Add(new Country() { CountryCode = "SL", CountryName = "Sierra Leone" });
      CountryList.Add(new Country() { CountryCode = "SG", CountryName = "Singapore" });
      CountryList.Add(new Country() { CountryCode = "SX", CountryName = "Sint Maarten (Dutch part)" });
      CountryList.Add(new Country() { CountryCode = "SK", CountryName = "Slovakia" });
      CountryList.Add(new Country() { CountryCode = "SI", CountryName = "Slovenia" });
      CountryList.Add(new Country() { CountryCode = "SB", CountryName = "Solomon Islands" });
      CountryList.Add(new Country() { CountryCode = "SO", CountryName = "Somalia" });
      CountryList.Add(new Country() { CountryCode = "ZA", CountryName = "South Africa" });
      CountryList.Add(new Country() { CountryCode = "GS", CountryName = "South Georgia and the South Sandwich Islands" });
      CountryList.Add(new Country() { CountryCode = "SS", CountryName = "South Sudan" });
      CountryList.Add(new Country() { CountryCode = "ES", CountryName = "Spain" });
      CountryList.Add(new Country() { CountryCode = "LK", CountryName = "Sri Lanka" });
      CountryList.Add(new Country() { CountryCode = "SD", CountryName = "Sudan" });
      CountryList.Add(new Country() { CountryCode = "SR", CountryName = "Suriname" });
      CountryList.Add(new Country() { CountryCode = "SJ", CountryName = "Svalbard and Jan Mayen" });
      CountryList.Add(new Country() { CountryCode = "SZ", CountryName = "Swaziland" });
      CountryList.Add(new Country() { CountryCode = "SE", CountryName = "Sweden" });
      CountryList.Add(new Country() { CountryCode = "CH", CountryName = "Switzerland" });
      CountryList.Add(new Country() { CountryCode = "SY", CountryName = "Syrian Arab Republic" });
      CountryList.Add(new Country() { CountryCode = "TW", CountryName = "Taiwan, Province of China" });
      CountryList.Add(new Country() { CountryCode = "TJ", CountryName = "Tajikistan" });
      CountryList.Add(new Country() { CountryCode = "TZ", CountryName = "Tanzania, United Republic of" });
      CountryList.Add(new Country() { CountryCode = "TH", CountryName = "Thailand" });
      CountryList.Add(new Country() { CountryCode = "TL", CountryName = "Timor-Leste" });
      CountryList.Add(new Country() { CountryCode = "TG", CountryName = "Togo" });
      CountryList.Add(new Country() { CountryCode = "TK", CountryName = "Tokelau" });
      CountryList.Add(new Country() { CountryCode = "TO", CountryName = "Tonga" });
      CountryList.Add(new Country() { CountryCode = "TT", CountryName = "Trinidad and Tobago" });
      CountryList.Add(new Country() { CountryCode = "TN", CountryName = "Tunisia" });
      CountryList.Add(new Country() { CountryCode = "TR", CountryName = "Turkey" });
      CountryList.Add(new Country() { CountryCode = "TM", CountryName = "Turkmenistan" });
      CountryList.Add(new Country() { CountryCode = "TC", CountryName = "Turks and Caicos Islands" });
      CountryList.Add(new Country() { CountryCode = "TV", CountryName = "Tuvalu" });
      CountryList.Add(new Country() { CountryCode = "UG", CountryName = "Uganda" });
      CountryList.Add(new Country() { CountryCode = "UA", CountryName = "Ukraine" });
      CountryList.Add(new Country() { CountryCode = "AE", CountryName = "United Arab Emirates" });
      CountryList.Add(new Country() { CountryCode = "GB", CountryName = "United Kingdom" });
      CountryList.Add(new Country() { CountryCode = "US", CountryName = "United States" });
      CountryList.Add(new Country() { CountryCode = "UM", CountryName = "United States Minor Outlying Islands" });
      CountryList.Add(new Country() { CountryCode = "UY", CountryName = "Uruguay" });
      CountryList.Add(new Country() { CountryCode = "UZ", CountryName = "Uzbekistan" });
      CountryList.Add(new Country() { CountryCode = "VU", CountryName = "Vanuatu" });
      CountryList.Add(new Country() { CountryCode = "VE", CountryName = "Venezuela, Bolivarian Republic of" });
      CountryList.Add(new Country() { CountryCode = "VN", CountryName = "Viet Nam" });
      CountryList.Add(new Country() { CountryCode = "VG", CountryName = "Virgin Islands, British" });
      CountryList.Add(new Country() { CountryCode = "VI", CountryName = "Virgin Islands, U.S." });
      CountryList.Add(new Country() { CountryCode = "WF", CountryName = "Wallis and Futuna" });
      CountryList.Add(new Country() { CountryCode = "EH", CountryName = "Western Sahara" });
      CountryList.Add(new Country() { CountryCode = "YE", CountryName = "Yemen,YE" });
      CountryList.Add(new Country() { CountryCode = "ZM", CountryName = "Zambia" });
      CountryList.Add(new Country() { CountryCode = "ZW", CountryName = "Zimbabwe" });

      return CountryList;
    }
  }
}